const header = {
  
}

const about = {
  // all the properties are optional - can be left empty or deleted
  name: 'Alexander Saavedra',
  role: 'Full Stack Software Engineer',
  description:
    'Full-stack software developer with a strong foundation in data science and artificial intelligence, holding a B.A. in Computer Science from Northwestern University. Proven expertise in developing and deploying innovative solutions, such as financial report parsers and alternative credit scoring models, using a diverse technology stack including Python, Java, Go, React, and Kubernetes.',
  resume: 'https://drive.google.com/file/d/1SjV0E30j-DM_oglbJ51f4t8XW2AD_jwH/view?usp=sharing',
  social: {
    linkedin: 'https://www.linkedin.com/in/saavedraa/',
    github: 'https://github.com/alexsaavedraa',
  },
}

const projects = [
  // projects can be added an removed
  // if there are no projects, Projects section won't show up
  {
    name: "Gold Medal Submission in Google's Prompt Recovery Challenge",
    description:
      'Given some text generated by a large language model, how do you predict what the input to that model was? Our model placed 13th/2175. Click the link to see a full length writeup and explanation',
    stack: ['Python', 'Genetic Algorithms', 'LLMS', 'Vectorizors'],
    sourceCode: 'https://github.com/alexsaavedraa/Prompt-Recovery-Challenge',
    livePreview: 'https://www.kaggle.com/competitions/llm-prompt-recovery',
  }
]

const skills = [
  // skills can be added or removed
  // if there are no skills, Skills section won't show up
  'Python',
  'C++',
  'JavaScript',
  'TypeScript',
  'React',
  'Pandas',
  'Transformers',
  'Material UI',
  'Git',
  'CI/CD',
  'Google Cloud',
  'NextJS',
  'AWS',
  'Kubernetes',
  'Docker'
]

const contact = {
  // email is optional - if left empty Contact section won't show up
  email: 'alexander.jsaavedra@gmail.com',
}

export { header, about, projects, skills, contact }
